// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_img

#ifndef _SQUARELINE_IMG_UI_H
#define _SQUARELINE_IMG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1492340486);   // assets/L50-Bg.png
LV_IMG_DECLARE( ui_img_310357668);   // assets/L7-embiggeroffsetscore.png
LV_IMG_DECLARE( ui_img_218071640);   // assets/L11-Score-embiggername.png
LV_IMG_DECLARE( ui_img_1264610442);   // assets/L15-Layer 22+.png
LV_IMG_DECLARE( ui_img_toncb_png);   // assets/Toncb.png
LV_IMG_DECLARE( ui_img_1685014530);   // assets/L40-Rounding.png
LV_IMG_DECLARE( ui_img_810505301);   // assets/L36-Honda.png
LV_IMG_DECLARE( ui_img_587546794);   // assets/L28-Tatami ++.png
LV_IMG_DECLARE( ui_img_1193668880);   // assets/L32-R1.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6tl_png);   // assets/buttoncorner6x6tl.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6tr_png);   // assets/buttoncorner6x6tr.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6_png);   // assets/buttoncorner6x6.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6br_png);   // assets/buttoncorner6x6br.png
LV_IMG_DECLARE( ui_img_leftarrow_png);   // assets/leftarrow.png
LV_IMG_DECLARE( ui_img_rightarrow_png);   // assets/rightarrow.png
LV_IMG_DECLARE( ui_img_rightarrow_invert_png);   // assets/rightarrow_invert.png
LV_IMG_DECLARE( ui_img_roll_5_frame_7_png);   // assets/roll_5_frame_7.png
LV_IMG_DECLARE( ui_img_836160992);   // assets/L11-Score.png
LV_IMG_DECLARE( ui_img_1801741918);   // assets/L18-Tatami +.png
LV_IMG_DECLARE( ui_img_641408904);   // assets/L33-R2.png
LV_IMG_DECLARE( ui_img_2052151144);   // assets/L34-R3.png
LV_IMG_DECLARE( ui_img_1690547480);   // assets/L35-R4.png
LV_IMG_DECLARE( ui_img_1512043842);   // assets/L7-Score+.png
LV_IMG_DECLARE( ui_img_buttoncorner_png);   // assets/buttoncorner.png
LV_IMG_DECLARE( ui_img_centernan_png);   // assets/centernan.png
LV_IMG_DECLARE( ui_img_roll_1_frame_7_png);   // assets/roll_1_frame_7.png
LV_IMG_DECLARE( ui_img_roll_1_inv_frame_7_png);   // assets/roll_1_inv_frame_7.png
LV_IMG_DECLARE( ui_img_roll_2_frame_7_png);   // assets/roll_2_frame_7.png
LV_IMG_DECLARE( ui_img_roll_2_inv_frame_7_png);   // assets/roll_2_inv_frame_7.png
LV_IMG_DECLARE( ui_img_roll_3_frame_7_png);   // assets/roll_3_frame_7.png
LV_IMG_DECLARE( ui_img_roll_3_inv_frame_7_png);   // assets/roll_3_inv_frame_7.png
LV_IMG_DECLARE( ui_img_roll_4_frame_7_png);   // assets/roll_4_frame_7.png
LV_IMG_DECLARE( ui_img_roll_4_inv_frame_7_png);   // assets/roll_4_inv_frame_7.png
LV_IMG_DECLARE( ui_img_roll_5_inv_frame_7_png);   // assets/roll_5_inv_frame_7.png
LV_IMG_DECLARE( ui_img_roll_6_frame_0_png);   // assets/roll_6_frame_0.png
LV_IMG_DECLARE( ui_img_roll_6_frame_1_png);   // assets/roll_6_frame_1.png
LV_IMG_DECLARE( ui_img_roll_6_frame_2_png);   // assets/roll_6_frame_2.png
LV_IMG_DECLARE( ui_img_roll_6_frame_3_png);   // assets/roll_6_frame_3.png
LV_IMG_DECLARE( ui_img_roll_6_frame_8_png);   // assets/roll_6_frame_8.png
LV_IMG_DECLARE( ui_img_roll_6_inv_frame_0_png);   // assets/roll_6_inv_frame_0.png
LV_IMG_DECLARE( ui_img_roll_6_inv_frame_1_png);   // assets/roll_6_inv_frame_1.png
LV_IMG_DECLARE( ui_img_roll_6_inv_frame_2_png);   // assets/roll_6_inv_frame_2.png
LV_IMG_DECLARE( ui_img_roll_6_inv_frame_3_png);   // assets/roll_6_inv_frame_3.png
LV_IMG_DECLARE( ui_img_roll_6_inv_frame_8_png);   // assets/roll_6_inv_frame_8.png
LV_IMG_DECLARE( ui_img_nancb_png);   // assets/Nancb.png
LV_IMG_DECLARE( ui_img_peicb_png);   // assets/Peicb.png
LV_IMG_DECLARE( ui_img_shack_png);   // assets/Shack.png
LV_IMG_DECLARE( ui_img_score_bigger_png);   // assets/score_bigger.png

// FONTS
LV_FONT_DECLARE( ui_font_windylg);
LV_FONT_DECLARE( ui_font_windymed);
LV_FONT_DECLARE( ui_font_windymedxlg);
LV_FONT_DECLARE( ui_font_windymx);
LV_FONT_DECLARE( ui_font_windysm);
LV_FONT_DECLARE( ui_font_windysmm);
LV_FONT_DECLARE( ui_font_segment20);
LV_FONT_DECLARE( ui_font_segment12);
LV_FONT_DECLARE( ui_font_windy18);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
