// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#ifndef _SQUARELINE_PROJECTTEST_UI_H
#define _SQUARELINE_PROJECTTEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * floatup_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * floatdown_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_buttoncorner6x6tl_png);   // assets/buttoncorner6x6tl.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6tr_png);   // assets/buttoncorner6x6tr.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6_png);   // assets/buttoncorner6x6.png
LV_IMG_DECLARE( ui_img_buttoncorner6x6br_png);   // assets/buttoncorner6x6br.png
LV_IMG_DECLARE( ui_img_leftarrow_png);   // assets/leftarrow.png
LV_IMG_DECLARE( ui_img_rightarrow_png);   // assets/rightarrow.png
LV_IMG_DECLARE( ui_img_rightarrow_invert_png);   // assets/rightarrow_invert.png

// FONTS
LV_FONT_DECLARE( ui_font_windylg);
LV_FONT_DECLARE( ui_font_windymed);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
