// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_img

#ifndef _SQUARELINE_IMG_UI_COMP_HOOK_H
#define _SQUARELINE_IMG_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Bar_create_hook( lv_obj_t *comp );
void ui_comp_blicon_create_hook( lv_obj_t *comp );
void ui_comp_player_create_hook( lv_obj_t *comp );

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
