// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#include "ui.h"

// COMPONENT Bar

lv_obj_t *ui_Bar_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_Bar;
cui_Bar = lv_bar_create(comp_parent);
lv_bar_set_range(cui_Bar, 0,180);
lv_bar_set_value(cui_Bar,25,LV_ANIM_OFF);
lv_bar_set_start_value(cui_Bar, 0, LV_ANIM_OFF);
lv_obj_set_height( cui_Bar, 10);
lv_obj_set_width( cui_Bar, lv_pct(100));
lv_obj_set_align( cui_Bar, LV_ALIGN_CENTER );
ui_object_set_themeable_style_property(cui_Bar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(cui_Bar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
ui_object_set_themeable_style_property(cui_Bar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(cui_Bar, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_OUTLINE_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_outline_width(cui_Bar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(cui_Bar, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(cui_Bar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(cui_Bar, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(cui_Bar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( cui_Bar, lv_obj_get_style_pad_right(cui_Bar,LV_PART_MAIN) + 1, LV_PART_MAIN );
lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BAR_NUM);
children[UI_COMP_BAR_BAR] = cui_Bar;
lv_obj_add_event_cb(cui_Bar, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_Bar, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_Bar_create_hook(cui_Bar);
return cui_Bar; 
}

