// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_img

#ifndef _UI_COMP_BLICON_H
#define _UI_COMP_BLICON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT blicon
#define UI_COMP_BLICON_BLICON 0
#define UI_COMP_BLICON_BLIMG 1
#define _UI_COMP_BLICON_NUM 2
lv_obj_t *ui_blicon_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
