// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

void ui_comp_Bar_create_hook( lv_obj_t * comp)
{
}

void ui_comp_player_create_hook( lv_obj_t * comp)
{
}
