// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#ifndef _UI_COMP_PLAYER_H
#define _UI_COMP_PLAYER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT player
#define UI_COMP_PLAYER_PLAYER 0
#define UI_COMP_PLAYER_PANEL8 1
#define UI_COMP_PLAYER_PANEL8_SCORE 2
#define UI_COMP_PLAYER_PANEL9 3
#define UI_COMP_PLAYER_PANEL9_RIICHI 4
#define UI_COMP_PLAYER_PANEL9_RIICHI_DOT 5
#define UI_COMP_PLAYER_PANEL9_CONTAINER 6
#define UI_COMP_PLAYER_PANEL9_CONTAINER_NAME 7
#define UI_COMP_PLAYER_PANEL9_CONTAINER_WIND 8
#define _UI_COMP_PLAYER_NUM 9
lv_obj_t *ui_player_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
