// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_img

#include "ui.h"

// COMPONENT player

lv_obj_t *ui_player_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_player;
cui_player = lv_obj_create(comp_parent);
lv_obj_set_width( cui_player, 265);
lv_obj_set_height( cui_player, 103);
lv_obj_set_x( cui_player, 14 );
lv_obj_set_y( cui_player, 95 );
lv_obj_set_align( cui_player, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_player, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_player, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_player, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Panel30;
cui_Panel30 = lv_obj_create(cui_player);
lv_obj_set_width( cui_Panel30, 80);
lv_obj_set_height( cui_Panel30, 24);
lv_obj_set_x( cui_Panel30, 9 );
lv_obj_set_y( cui_Panel30, -3 );
lv_obj_set_align( cui_Panel30, LV_ALIGN_BOTTOM_LEFT );
lv_obj_remove_flag( cui_Panel30, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( cui_Panel30, &ui_img_310357668, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Panel30, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_offsetscore;
cui_offsetscore = lv_label_create(cui_Panel30);
lv_obj_set_width( cui_offsetscore, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_offsetscore, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_offsetscore, 9 );
lv_obj_set_y( cui_offsetscore, 0 );
lv_obj_set_align( cui_offsetscore, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_offsetscore,"-3000");
ui_object_set_themeable_style_property(cui_offsetscore, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(cui_offsetscore, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_text_align(cui_offsetscore, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_offsetscore, &ui_font_windy18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_offsetscore, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_offsetscore, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_offsetscore, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_offsetscore, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_container;
cui_container = lv_obj_create(cui_player);
lv_obj_set_width( cui_container, 112);
lv_obj_set_height( cui_container, 25);
lv_obj_set_x( cui_container, -4 );
lv_obj_set_y( cui_container, -2 );
lv_obj_set_align( cui_container, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_remove_flag( cui_container, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( cui_container, &ui_img_218071640, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(cui_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_container, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_name;
cui_name = lv_label_create(cui_container);
lv_obj_set_width( cui_name, 80);
lv_obj_set_height( cui_name, 13);
lv_obj_set_x( cui_name, 6 );
lv_obj_set_y( cui_name, 0 );
lv_obj_set_align( cui_name, LV_ALIGN_CENTER );
lv_label_set_long_mode(cui_name,LV_LABEL_LONG_MODE_DOTS);
lv_label_set_text(cui_name,"");
ui_object_set_themeable_style_property(cui_name, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(cui_name, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_White);
lv_obj_set_style_text_align(cui_name, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_name, &ui_font_windy18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_name, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_name, -3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_name, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_dot;
cui_dot = lv_obj_create(cui_container);
lv_obj_set_width( cui_dot, 7);
lv_obj_set_height( cui_dot, 7);
lv_obj_set_x( cui_dot, -48 );
lv_obj_set_y( cui_dot, 0 );
lv_obj_set_align( cui_dot, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_dot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_dot, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_dot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(cui_dot, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_border_width(cui_dot, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Panel8;
cui_Panel8 = lv_obj_create(cui_player);
lv_obj_set_width( cui_Panel8, 91);
lv_obj_set_height( cui_Panel8, 26);
lv_obj_set_x( cui_Panel8, -13 );
lv_obj_set_y( cui_Panel8, -37 );
lv_obj_set_align( cui_Panel8, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_image_src( cui_Panel8, &ui_img_1264610442, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_width(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Panel8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_score;
cui_score = lv_label_create(cui_Panel8);
lv_obj_set_width( cui_score, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_score, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_score, 0 );
lv_obj_set_y( cui_score, 1 );
lv_obj_set_align( cui_score, LV_ALIGN_CENTER );
lv_label_set_text(cui_score,"930000");
ui_object_set_themeable_style_property(cui_score, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(cui_score, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_text_font(cui_score, &ui_font_segment20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_score, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_score, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_score, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_score, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_score, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_windimg;
cui_windimg = lv_image_create(cui_player);
lv_image_set_src(cui_windimg, &ui_img_toncb_png);
lv_obj_set_width( cui_windimg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_windimg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_windimg, -13 );
lv_obj_set_y( cui_windimg, -1 );
lv_obj_set_align( cui_windimg, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( cui_windimg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( cui_windimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PLAYER_NUM);
children[UI_COMP_PLAYER_PLAYER] = cui_player;
children[UI_COMP_PLAYER_PANEL30] = cui_Panel30;
children[UI_COMP_PLAYER_PANEL30_OFFSETSCORE] = cui_offsetscore;
children[UI_COMP_PLAYER_CONTAINER] = cui_container;
children[UI_COMP_PLAYER_CONTAINER_NAME] = cui_name;
children[UI_COMP_PLAYER_CONTAINER_DOT] = cui_dot;
children[UI_COMP_PLAYER_PANEL8] = cui_Panel8;
children[UI_COMP_PLAYER_PANEL8_SCORE] = cui_score;
children[UI_COMP_PLAYER_WINDIMG] = cui_windimg;
lv_obj_add_event_cb(cui_player, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_player, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_player_create_hook(cui_player);
return cui_player; 
}

