// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_img

#include "ui.h"

// COMPONENT blicon

lv_obj_t *ui_blicon_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_blicon;
cui_blicon = lv_obj_create(comp_parent);
lv_obj_set_width( cui_blicon, 16);
lv_obj_set_height( cui_blicon, 16);
lv_obj_set_x( cui_blicon, -16 );
lv_obj_set_y( cui_blicon, 33 );
lv_obj_set_align( cui_blicon, LV_ALIGN_CENTER );
lv_obj_remove_flag( cui_blicon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_blicon, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(cui_blicon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(cui_blicon, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_border_width(cui_blicon, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_blicon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_blicon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_blicon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_blicon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_blimg;
cui_blimg = lv_image_create(cui_blicon);
lv_image_set_src(cui_blimg, &ui_img_buttoncorner6x6_png);
lv_obj_set_width( cui_blimg, LV_SIZE_CONTENT);  /// 6
lv_obj_set_height( cui_blimg, LV_SIZE_CONTENT);   /// 6
lv_obj_set_align( cui_blimg, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_blimg, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( cui_blimg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_transform_rotation(cui_blimg, 2700, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_transform_pivot_x(cui_blimg, 2, LV_PART_MAIN| LV_STATE_USER_2);
lv_obj_set_style_transform_pivot_y(cui_blimg, 2, LV_PART_MAIN| LV_STATE_USER_2);

lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BLICON_NUM);
children[UI_COMP_BLICON_BLICON] = cui_blicon;
children[UI_COMP_BLICON_BLIMG] = cui_blimg;
lv_obj_add_event_cb(cui_blicon, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_blicon, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_blicon_create_hook(cui_blicon);
return cui_blicon; 
}

