// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern void ui_event_Panel2( lv_event_t * e);
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Chart1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Panel2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

