// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern void ui_event_Panel1( lv_event_t * e);
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_player1;
extern lv_obj_t *ui_player3;
extern lv_obj_t *ui_player2;
extern lv_obj_t *ui_player4;
extern lv_obj_t *ui_roundpane;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_roundwind;
extern lv_obj_t *ui_roundnum;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_riichi2;
extern lv_obj_t *ui_dot2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_riichi1;
extern lv_obj_t *ui_dot1;
extern lv_obj_t *ui_dot3;
extern lv_obj_t *ui_dot4;
extern lv_obj_t *ui_dot5;
extern lv_obj_t *ui_dot6;
extern lv_obj_t *ui_dot7;
extern lv_obj_t *ui_dot8;
extern lv_obj_t *ui_dot9;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_modalcontainer;
extern void ui_event_modal( lv_event_t * e);
extern lv_obj_t *ui_modal;
extern lv_obj_t *ui_modalcontent;
extern lv_obj_t *ui_win1;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_blicon4;
extern lv_obj_t *ui_blimg4;
extern lv_obj_t *ui_Panel16;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_blicon5;
extern lv_obj_t *ui_blimg5;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_blicon1;
extern lv_obj_t *ui_blimg1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_bricon;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_cancel;
extern lv_obj_t *ui_bricon1;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_draw;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_bricon4;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_win2;
extern lv_obj_t *ui_Panel10;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_Panel11;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_blicon2;
extern lv_obj_t *ui_blimg2;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_blicon3;
extern lv_obj_t *ui_blimg3;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_prev;
extern lv_obj_t *ui_bricon3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_draw1;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_bricon5;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_modalplayer;
// CUSTOM VARIABLES
extern lv_obj_t *uic_modalplayer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

