// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Panel2;
lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Bar3 = NULL;lv_obj_t *ui_Bar4 = NULL;lv_obj_t *ui_Bar2 = NULL;
// event funtions
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_NEXT  ) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
}
}

void ui_event_Panel2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_DOWN  ) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Screen1_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel2, 289);
lv_obj_set_height( ui_Panel2, 191);
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Bar1 = lv_bar_create(ui_Panel2);
lv_bar_set_mode(ui_Bar1, LV_BAR_MODE_RANGE);
lv_bar_set_range(ui_Bar1, 0,180);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_width( ui_Bar1, lv_pct(100));
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Bar1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar1,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar1, lv_obj_get_style_pad_right(ui_Bar1,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Bar3 = lv_bar_create(ui_Panel2);
lv_bar_set_range(ui_Bar3, 0,180);
lv_bar_set_value(ui_Bar3,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_Bar3, 10);
lv_obj_set_width( ui_Bar3, lv_pct(100));
lv_obj_set_align( ui_Bar3, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Bar3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Bar3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar3, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar3, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar3,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar3, lv_obj_get_style_pad_right(ui_Bar3,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Bar4 = lv_bar_create(ui_Panel2);
lv_bar_set_range(ui_Bar4, 0,180);
lv_bar_set_value(ui_Bar4,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar4, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_Bar4, 10);
lv_obj_set_width( ui_Bar4, lv_pct(100));
lv_obj_set_align( ui_Bar4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Bar4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Bar4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Bar4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar4, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar4, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar4,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar4, lv_obj_get_style_pad_right(ui_Bar4,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Bar2 = lv_bar_create(ui_Panel2);
lv_bar_set_range(ui_Bar2, 0,180);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_height( ui_Bar2, 10);
lv_obj_set_width( ui_Bar2, lv_pct(100));
lv_obj_set_x( ui_Bar2, 0 );
lv_obj_set_y( ui_Bar2, -3 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Bar2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Bar2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Bar2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Bar2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Bar2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Bar2,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Bar2, lv_obj_get_style_pad_right(ui_Bar2,LV_PART_MAIN) + 1, LV_PART_MAIN );
lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);
uic_Panel2 = ui_Panel2;

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
uic_Panel2= NULL;
ui_Panel2= NULL;
ui_Bar1= NULL;
ui_Bar3= NULL;
ui_Bar4= NULL;
ui_Bar2= NULL;

}
