// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#include "ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Bar2 = NULL;lv_obj_t *ui_Bar3 = NULL;lv_obj_t *ui_Bar4 = NULL;
// event funtions
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_NEXT  ) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_OUT_RIGHT, 300, 0, &ui_Screen1_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Screen2);
lv_obj_set_width( ui_Panel2, 300);
lv_obj_set_height( ui_Panel2, 300);
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Sensors");
ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Label1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_Label1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_border_width(ui_Label1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Label1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar1 = ui_Bar_create(ui_Panel2);
lv_obj_set_x( ui_Bar1, 0 );
lv_obj_set_y( ui_Bar1, 0 );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
ui_Bar2 = ui_Bar_create(ui_Panel2);
lv_bar_set_range(ui_Bar2, 0,180);
lv_obj_set_x( ui_Bar2, 0 );
lv_obj_set_y( ui_Bar2, 0 );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
ui_Bar3 = ui_Bar_create(ui_Panel2);
lv_bar_set_range(ui_Bar3, 0,180);
lv_obj_set_x( ui_Bar3, 0 );
lv_obj_set_y( ui_Bar3, 0 );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
ui_Bar4 = ui_Bar_create(ui_Panel2);
lv_bar_set_range(ui_Bar4, 0,180);
lv_obj_set_x( ui_Bar4, 0 );
lv_obj_set_y( ui_Bar4, 0 );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Panel2= NULL;
ui_Label1= NULL;
ui_Bar1= NULL;
ui_Bar2= NULL;
ui_Bar3= NULL;
ui_Bar4= NULL;

}
