// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1( lv_event_t * e);
extern lv_obj_t *ui_Screen1;
extern void ui_event_Panel1( lv_event_t * e);
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_player1;
extern lv_obj_t *ui_player3;
extern lv_obj_t *ui_player2;
extern lv_obj_t *ui_player4;
extern lv_obj_t *ui_roundpane;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_roundwind;
extern lv_obj_t *ui_roundnum;
extern lv_obj_t *ui_Panel6;
extern lv_obj_t *ui_riichi2;
extern lv_obj_t *ui_dot2;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_riichi1;
extern lv_obj_t *ui_dot1;
extern lv_obj_t *ui_dot3;
extern lv_obj_t *ui_dot4;
extern lv_obj_t *ui_dot5;
extern lv_obj_t *ui_dot6;
extern lv_obj_t *ui_dot7;
extern lv_obj_t *ui_dot8;
extern lv_obj_t *ui_dot9;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

