// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.3
// Project name: SquareLine_Projecttest

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_player1 = NULL;lv_obj_t *ui_player3 = NULL;lv_obj_t *ui_player2 = NULL;lv_obj_t *ui_player4 = NULL;lv_obj_t *ui_roundpane = NULL;lv_obj_t *ui_Panel7 = NULL;lv_obj_t *ui_roundwind = NULL;lv_obj_t *ui_roundnum = NULL;lv_obj_t *ui_Panel6 = NULL;lv_obj_t *ui_riichi2 = NULL;lv_obj_t *ui_dot2 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_riichi1 = NULL;lv_obj_t *ui_dot1 = NULL;lv_obj_t *ui_dot3 = NULL;lv_obj_t *ui_dot4 = NULL;lv_obj_t *ui_dot5 = NULL;lv_obj_t *ui_dot6 = NULL;lv_obj_t *ui_dot7 = NULL;lv_obj_t *ui_dot8 = NULL;lv_obj_t *ui_dot9 = NULL;lv_obj_t *ui_Label3 = NULL;
// event funtions
void ui_event_Screen1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_NEXT  ) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_OUT_TOP, 300, 0, &ui_Screen2_screen_init);
}
}

void ui_event_Panel1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_NEXT  ) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_OUT_LEFT, 500, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 300);
lv_obj_set_height( ui_Panel1, 300);
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_player1 = ui_player_create(ui_Panel1);
lv_obj_set_x( ui_player1, 17 );
lv_obj_set_y( ui_player1, 133 );
lv_obj_remove_flag( ui_player1, LV_OBJ_FLAG_HIDDEN );    /// Flags
lv_obj_set_style_transform_rotation(ui_player1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_player3 = ui_player_create(ui_Panel1);
lv_obj_set_x( ui_player3, 243 );
lv_obj_set_y( ui_player3, -107 );
lv_obj_set_style_transform_rotation(ui_player3, 1800, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_player2 = ui_player_create(ui_Panel1);
lv_obj_set_x( ui_player2, 10 );
lv_obj_set_y( ui_player2, -101 );
lv_obj_set_style_transform_rotation(ui_player2, 900, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_player4 = ui_player_create(ui_Panel1);
lv_obj_set_x( ui_player4, 252 );
lv_obj_set_y( ui_player4, 126 );
lv_obj_set_style_transform_rotation(ui_player4, 2700, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_roundpane = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_roundpane, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_roundpane, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_roundpane, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_roundpane,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_roundpane, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_roundpane, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_roundpane, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_roundpane, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_roundpane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_roundpane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_roundpane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_roundpane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_roundpane, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_roundpane);
lv_obj_set_width( ui_Panel7, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel7, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_roundwind = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_roundwind, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_roundwind, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_roundwind, LV_ALIGN_CENTER );
lv_label_set_text(ui_roundwind,"東");
lv_obj_set_style_text_font(ui_roundwind, &ui_font_windylg, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_roundnum = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_roundnum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_roundnum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_roundnum, LV_ALIGN_CENTER );
lv_label_set_text(ui_roundnum,"1");
ui_object_set_themeable_style_property(ui_roundnum, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_roundnum, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_White);
lv_obj_set_style_text_align(ui_roundnum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_roundnum, &ui_font_windylg, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_roundnum, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_roundnum, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_roundnum, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_pad_left(ui_roundnum, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_roundnum, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_roundnum, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_roundnum, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_roundpane);
lv_obj_set_width( ui_Panel6, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Panel6, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Panel6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Panel6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_riichi2 = lv_obj_create(ui_Panel6);
lv_obj_set_width( ui_riichi2, 23);
lv_obj_set_height( ui_riichi2, 40);
lv_obj_set_align( ui_riichi2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_riichi2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_riichi2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_riichi2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_riichi2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_riichi2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_border_width(ui_riichi2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot2 = lv_obj_create(ui_riichi2);
lv_obj_set_width( ui_dot2, 10);
lv_obj_set_height( ui_dot2, 10);
lv_obj_set_align( ui_dot2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"x3");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_riichi1 = lv_obj_create(ui_Panel6);
lv_obj_set_width( ui_riichi1, 23);
lv_obj_set_height( ui_riichi1, 40);
lv_obj_set_align( ui_riichi1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_riichi1,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_riichi1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_riichi1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_riichi1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Black);
ui_object_set_themeable_style_property(ui_riichi1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Black);
lv_obj_set_style_border_width(ui_riichi1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_riichi1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_riichi1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_riichi1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_riichi1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_riichi1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_riichi1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_riichi1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_riichi1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_riichi1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_riichi1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_riichi1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_riichi1, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_dot1 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot1, 4);
lv_obj_set_height( ui_dot1, 4);
lv_obj_set_align( ui_dot1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot1, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot3 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot3, 4);
lv_obj_set_height( ui_dot3, 4);
lv_obj_set_align( ui_dot3, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot4 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot4, 4);
lv_obj_set_height( ui_dot4, 4);
lv_obj_set_align( ui_dot4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot4, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot5 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot5, 4);
lv_obj_set_height( ui_dot5, 4);
lv_obj_set_align( ui_dot5, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot5, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot5, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot6 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot6, 4);
lv_obj_set_height( ui_dot6, 4);
lv_obj_set_align( ui_dot6, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot6, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot7 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot7, 4);
lv_obj_set_height( ui_dot7, 4);
lv_obj_set_align( ui_dot7, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot7, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot8 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot8, 4);
lv_obj_set_height( ui_dot8, 4);
lv_obj_set_align( ui_dot8, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot8, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot8, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dot9 = lv_obj_create(ui_riichi1);
lv_obj_set_width( ui_dot9, 4);
lv_obj_set_height( ui_dot9, 4);
lv_obj_set_align( ui_dot9, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_dot9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_dot9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_White);
ui_object_set_themeable_style_property(ui_dot9, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_White);
lv_obj_set_style_border_width(ui_dot9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"x3");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
ui_player1= NULL;
ui_player3= NULL;
ui_player2= NULL;
ui_player4= NULL;
ui_roundpane= NULL;
ui_Panel7= NULL;
ui_roundwind= NULL;
ui_roundnum= NULL;
ui_Panel6= NULL;
ui_riichi2= NULL;
ui_dot2= NULL;
ui_Label5= NULL;
ui_riichi1= NULL;
ui_dot1= NULL;
ui_dot3= NULL;
ui_dot4= NULL;
ui_dot5= NULL;
ui_dot6= NULL;
ui_dot7= NULL;
ui_dot8= NULL;
ui_dot9= NULL;
ui_Label3= NULL;

}
